### ISSUE TITLE
school blocking

### ISSUE THREAD

**Issue by easella** [QuiteAFancyEmerald/Holy-Unblocker#61]
![image](https://user-images.githubusercontent.com/74786054/114419154-3065da80-9b81-11eb-85e1-475adf3a4f27.png)

![image](https://user-images.githubusercontent.com/74786054/114419178-36f45200-9b81-11eb-87f1-92c18fd38f88.png)

![image](https://user-images.githubusercontent.com/74786054/114419205-3c519c80-9b81-11eb-9dd5-647c35e4d66d.png)

![image](https://user-images.githubusercontent.com/74786054/114419238-41aee700-9b81-11eb-90d5-8a539aafe0d0.png)

**Comment by SkidFace** [comment]
aight, make sure you check other issues, because this is a commonly asked one, but here's what you want to do:

Step 1: At home, use this link: https://discord.gg/hcUUceSCtj 
This is the titanium network's discord. 

Step 2: Go to #bot-commands and type: %proxy hu 
(this is a link that redirects to the main website)

Step 3: Write that on a piece of paper and use that link.

NOTE: if the new link gets blocked, you can always request for a new link. (I think you get a max of 3 a month per account)

**Comment by QuiteAFancyEmerald** [comment]
Yeah, do what @SkidFace said. :D
